Bonjour §model.UserName§, <br />
<br />
	Nous vous confirmons que votre site §model.SiteName§ est disponible à l'adresse:<br />
		<a href="§model.SiteUrl§">§model.SiteUrl§</a><br />
<br />
	Vous pouvez l'administrer à partir de l'adresse:<br />
		<a href="§model.SiteUrl§administration">§model.SiteUrl§administration</a><br />
<br />
Cordialement,<br />

Guillaume Chervet<br />
guillaume.chervet@bworld.fr<br />
0676975613<br />
<a href="https://www.bworld.fr">https://www.bworld.fr</a>