Bonjour §model.UserName§, <br />
<br />
	Suite à la perte ou l'oubli de votre mot de passe, vous avez demandé à re-initialiser celui-ci. 
	Si cet email n'est pas issu de votre part, ne cliquez surtout pas sur le lien ci-dessous.<br /><br />
	Si vous souhaitez réellement changer votre mot de passe, cliquer sur le lien suivant: 
	<br />
	<a href="§model.CallbackUrl§">§model.CallbackUrl§</a><br />
<br />
Cordialement,<br />
Guillaume Chervet<br />
guillaume.chervet@bworld.fr<br />
0676975613<br />
<a href="https://www.bworld.fr">https://www.bworld.fr</a>