Bonjour, <br />
<br />
	Vous avez été ajouté par §model.AdderUserName§ en tant qu'administrateur au site §model.SiteName§ qui est disponible à l'adresse:<br />
		<a href="§model.SiteUrl§">§model.SiteUrl§</a><br />
<br />
	Avant de pouvoir l'administrer vous devez vous inscrire avec l'adresse email avec laquelle vous avez reçu ce mail à l'adresse (l'adresse email devra être validée):<br />
		<a href="§model.SiteUrl§/connexion">§model.SiteUrl§/utilisateur/connexion</a><br />
<br />
Cordialement,<br />
Service Client bworld,<br />
<a href="https://www.bworld.fr">https://www.bworld.fr</a>