Bonjour §model.UserName§, <br />
<br />
	Vous avez été ajouté par §model.AdderUserName§ en tant qu'administrateur au site §model.SiteName§ qui est disponible à l'adresse:<br />
		<a href="§model.SiteUrl§">§model.SiteUrl§</a><br />
<br />
	Vous pouvez l'administrer à partir de l'adresse:<br />
		<a href="§model.SiteUrl§/administration">§model.SiteUrl§/administration</a><br />
<br />
Cordialement,<br />
Service Client bworld,<br />
<a href="https://www.bworld.fr">https://www.bworld.fr</a>